# Configure renderer backends based on platform
# This mimics the logic from src/config.h

if(NOT DEFINED BGFX_CONFIG_RENDERER_DIRECT3D11)
    if(WIN32 OR LINUX)
        set(BGFX_CONFIG_RENDERER_DIRECT3D11 1)
    else()
        set(BGFX_CONFIG_RENDERER_DIRECT3D11 0)
    endif()
endif()

if(NOT DEFINED BGFX_CONFIG_RENDERER_DIRECT3D12)
    if(WIN32 OR LINUX)
        set(BGFX_CONFIG_RENDERER_DIRECT3D12 1)
    else()
        set(BGFX_CONFIG_RENDERER_DIRECT3D12 0)
    endif()
endif()

if(NOT DEFINED BGFX_CONFIG_RENDERER_OPENGL)
    if(LINUX OR WIN32)
        set(BGFX_CONFIG_RENDERER_OPENGL 1)
    else()
        set(BGFX_CONFIG_RENDERER_OPENGL 0)
    endif()
endif()

if(NOT DEFINED BGFX_CONFIG_RENDERER_OPENGLES)
    if(ANDROID OR EMSCRIPTEN)
        set(BGFX_CONFIG_RENDERER_OPENGLES 30)
    else()
        set(BGFX_CONFIG_RENDERER_OPENGLES 0)
    endif()
endif()

if(NOT DEFINED BGFX_CONFIG_RENDERER_VULKAN)
    if(ANDROID OR LINUX OR WIN32 OR APPLE)
        set(BGFX_CONFIG_RENDERER_VULKAN 1)
    else()
        set(BGFX_CONFIG_RENDERER_VULKAN 0)
    endif()
endif()

if(NOT DEFINED BGFX_CONFIG_RENDERER_METAL)
    if(APPLE)
        set(BGFX_CONFIG_RENDERER_METAL 1)
    else()
        set(BGFX_CONFIG_RENDERER_METAL 0)
    endif()
endif()

if(NOT DEFINED BGFX_CONFIG_RENDERER_NOOP)
    set(BGFX_CONFIG_RENDERER_NOOP 0)
endif()

# Set compile definitions
set(BGFX_DEFINES)

if(BGFX_CONFIG_RENDERER_DIRECT3D11)
    list(APPEND BGFX_DEFINES BGFX_CONFIG_RENDERER_DIRECT3D11=1)
endif()

if(BGFX_CONFIG_RENDERER_DIRECT3D12)
    list(APPEND BGFX_DEFINES BGFX_CONFIG_RENDERER_DIRECT3D12=1)
endif()

if(BGFX_CONFIG_RENDERER_OPENGL)
    list(APPEND BGFX_DEFINES BGFX_CONFIG_RENDERER_OPENGL=${BGFX_CONFIG_RENDERER_OPENGL})
endif()

if(BGFX_CONFIG_RENDERER_OPENGLES)
    list(APPEND BGFX_DEFINES BGFX_CONFIG_RENDERER_OPENGLES=${BGFX_CONFIG_RENDERER_OPENGLES})
endif()

if(BGFX_CONFIG_RENDERER_VULKAN)
    list(APPEND BGFX_DEFINES BGFX_CONFIG_RENDERER_VULKAN=1)
endif()

if(BGFX_CONFIG_RENDERER_METAL)
    list(APPEND BGFX_DEFINES BGFX_CONFIG_RENDERER_METAL=1)
endif()

if(BGFX_CONFIG_RENDERER_NOOP)
    list(APPEND BGFX_DEFINES BGFX_CONFIG_RENDERER_NOOP=1)
endif()

# Additional defines
list(APPEND BGFX_DEFINES
    BGFX_CONFIG_RENDERER_USE_EXTENSIONS=1
    BGFX_CONFIG_USE_TINYSTL=1
    BGFX_CONFIG_MULTITHREADED=1
)

# Debug/Release defines
if(CMAKE_BUILD_TYPE STREQUAL "Debug")
    list(APPEND BGFX_DEFINES
        BX_CONFIG_DEBUG=1
        BGFX_CONFIG_DEBUG=1
        BGFX_CONFIG_DEBUG_ANNOTATION=1
        BGFX_CONFIG_DEBUG_OBJECT_NAME=1
        BGFX_CONFIG_DEBUG_UNIFORM=1
        BGFX_CONFIG_DEBUG_OCCLUSION=1
    )
else()
    list(APPEND BGFX_DEFINES
        BX_CONFIG_DEBUG=0
        BGFX_CONFIG_DEBUG=0
        BGFX_CONFIG_DEBUG_ANNOTATION=0
        BGFX_CONFIG_DEBUG_OBJECT_NAME=0
        BGFX_CONFIG_DEBUG_UNIFORM=0
        BGFX_CONFIG_DEBUG_OCCLUSION=0
    )
endif()

# Profiler
if(BGFX_BUILD_WITH_PROFILER)
    list(APPEND BGFX_DEFINES
        ENTRY_CONFIG_PROFILER=1
        BGFX_CONFIG_PROFILER=1
    )
endif()

# Apply defines to target (will be set in main CMakeLists.txt)
# Note: Using include() so variables are set in current scope, not PARENT_SCOPE
set(BGFX_COMPILE_DEFINITIONS ${BGFX_DEFINES})

